### ISSUE TITLE
Criar Protótipo de Alta Fidelidade

### ISSUE THREAD

**Issue by victoralvesgomide** [Interacao-Humano-Computador/2019.2-Wish#13]
- [x] Definir ferramenta a ser utilizada;
- [ ] Criar um conjunto de telas para cada sugestão de melhoria.
  * As sugestões estão descritas em um [documento](https://docs.google.com/document/d/1o_XJCWsLyT5zDVjvmfqj9DhawViDlHizbPESpV-4IOk/edit);
  * Mínimo de três sugestões.
---
**OBSERVAÇÕES**
- Pode-se utilizar:
  * O próprio [site](https://www.wish.com/);
  * O protótipo de papel existente;
  * A definição da identidade visual.
- A escolha da ferramenta, o link para o protótipo e algumas capturas de tela devem ser documentados em um arquivo .md (Markdown), para que posteriormente sejam adicionados à nossa [Wiki](https://interacao-humano-computador.github.io/2019.2-Wish/).

**Comment by guilhesme23** [comment]
Ferramenta sendo utilizada até o momento: Figma

O link para o projeto está aqui:

https://www.figma.com/file/IwJZtqVZZnFL7iUFEn1zEG/Untitled?node-id=0%3A1
